# docker compose file with one rabbitmq service. It has two vhosta
# and two users. One user is admin and the other is a regular user.
version: "3"
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
